### ISSUE TITLE
Wallet no longer showing balance

### ISSUE THREAD

**Issue by dbwest** [HOdlcoin/coinomi-android#13]
I had roughly 1k hodlcoin from a mining experiment. The coins are now missing. The wallet has a zero balance, says 1 previous address is unused (it is not), and says "trouble connecting". I have reset my Android, changed from WiFi to cellular data, etc. Still no balance.

**Comment by amit177** [comment]
You are having this issue because the server that hosts it is currently down.
It's being worked on.

**Comment by amit177** [comment]
This has been fixed.
